# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4b7095353ee045c7723d75eedc6adc2fe29387fdee8ff1ca1ea82e7f46001eb6cfc56f47a3ae66eb3f753ea921b71d1376d59b7fd3218afab3d286f841f319

test:
  secret_key_base: b1291e29c8915c2248b2bb608038ce9e5663ee59def4b838e5e0c281480318961e8d9932bc3877a43e44df08d61e1a9d48822953d55656cc6a7e145cf710b5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
